### ISSUE TITLE
Milestone 0.0.2 issues

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#109]
@lightandluck we talked about making a tracking issue for the remaining v0.0.2 work. I started a task list, but had some questions. Could we huddle on this?

- [ ] ~Ansible deployment~

- [x] **Review and merge**: Get versions from `/versions` endpoint in Scanner - edgi-govdata-archiving/web-monitoring-ui#218 (Has been deployed)

- [x] **Merge and deploy script to ingest IA**: edgi-govdata-archiving/web-monitoring-processing#174

- [x] **Approve and merge**: Different or ?skip_unchanged imports - edgi-govdata-archiving/web-monitoring-db#288

- [x] Change parameter in scraper that creates analysts sheets to pull from IA source instead of Versionista ([code that does it](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/blob/master/bin/query-db-and-email))

- [x] **Review and merge**: Remove ?include_version - edgi-govdata-archiving/web-monitoring-db#264 _(After convo with Rob at 2018/5/9 meeting, this is not absolutely needed for 0.0.2, but it's nice that we have it ready)_

**Comment by lightandluck** [comment]
Hey Ray, most of the work has PRs that just need to be approved, merged, and deployed. There's one issue without a PR edgi-govdata-archiving/web-monitoring-db#264, which I can work on. 

It's fairly straightforward. I spent some time digging through the code and learning some Ruby. I probably won't do it idiomatically and Rob will need to touch it up, but I think it's worthwhile for me to make changes to -db for the experience. I'll probably have a PR ready tomorrow.

**Comment by weatherpattern** [comment]
That's great. Thanks for the update.

**Comment by Mr0grog** [comment]
Ugh, my remedial slowness has single-handedly held this up. But it is not stale. 😞

**Comment by lightandluck** [comment]
Not your fault! Getting data from Wayback has not been easy at all, especially working on your own. Wish we could help more

**Comment by Mr0grog** [comment]
This all happened a while back now; closing.
