### ISSUE TITLE
Document Release & Deploy Process

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#138]
We need to actually document our release and deployment processes. We should:

- [x] ~Briefly describe them in this repo. (Projects have a `release` branch that auto-builds & publishes Docker images; we deploy them manually and store Kubernetes, etc. configs in -ops.)~ (PR: #140) *(Update: ultimately decided to just delete this info, since it’s too easy to get out of sync with web-monitoring-ops.)*

- [x] In -ops, explain:
    - How we update configs and use Docker image tags
    - Where we publish/pull Docker images from (https://hub.docker.com/u/envirodgi)
    - How we deploy other stuff (the `manually-managed` folder)
    - Proposed changes: edgi-govdata-archiving/web-monitoring-ops#27

- [x] In code repos, explain how `release` branch works.
    - [x] -ui (edgi-govdata-archiving/web-monitoring-ui#420)
    - [x] -db (edgi-govdata-archiving/web-monitoring-db#617)
    - [x] -processing (edgi-govdata-archiving/web-monitoring-processing#496)
    - ❌ -versionista-scraper (not really applicable)

**Comment by SYU15** [comment]
Thanks for creating this issue! Agreed this would be very helpful. Also could we maybe include a list of people who have deployment credentials so we know who to go to if there are production issues?

Seems like this documentation is out of date: https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/ARCHITECTURE.md#deployment-plan. Is this where you were planning on adding it? Otherwise perhaps it can be removed to avoid confusion.

**Comment by Mr0grog** [comment]
> Seems like this documentation is out of date: [/ARCHITECTURE.md@`master`#deployment-plan](https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/ARCHITECTURE.md#deployment-plan) [](/edgi-govdata-archiving/web-monitoring/blob/HEAD@{2019-08-09T00:57:16Z}/ARCHITECTURE.md#deployment-plan)

Oh geez, yeah, that’s super out of date. We’ve been running everything on AWS and mostly on Kubernetes for a while now.

That might be the right place to put this stuff, but maybe it needs to be a separate doc. Haven’t thought it through — made this issue to dump a quick outline down before I forgot it.

**Comment by Mr0grog** [comment]
Added a PR to update the architecture doc in #140.

**Comment by Mr0grog** [comment]
This is done!
