### ISSUE TITLE
Put this project to rest

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#168]
It is time to put this project more-or-less to rest. EDGI no longer makes active use of most of the web monitoring in this and the associated web-monitoring-xyz repos, although the web governance team (the team was renamed) currently wants it to keep *running* in a minimal capacity. At current, I feel a lot of responsibility to keep close watch over the running servers and tools, but that needs to stop.

**This does not apply to two subprojects that are actively used outside EDGI:**
1. [wayback](https://github.com/edgi-govdata-archiving/wayback/)
2. [web-monitoring-diff](https://github.com/edgi-govdata-archiving/web-monitoring-diff) (One nice thing about keeping the other tools running in a minimal way is that it provides a place to test changes to this.)

Anyway, things that probably need to get done here in order for me to largely step away:

- [x] ❌ ~Stop monitoring as many currently active URLs as possible. As of December 2022, we cut the number of URLs in half, and I am going to look through and see what else might make sense to turn off.~ *(2023-01-24 Additional work here is probably not worth spending effort on. I’m going to leave it be.)*

- [x] Fix issues with bad page titles because of responses that are errors: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/751 (PR: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/1061)

- [x] Do not require auth for reading the API. One thing auth is currently doing for us is preventing broader abuse of the API, so there are some sizable sub-issues here:

    - [x] Use efficient range-based (instead of offset-based) pagination for versions (where this is a huge problem) and optionally other models. This also means limiting the options for the `sort` parameter. https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/579

    - [x] ❌ ~Maybe denormalize important fields we currently have to do complex and expensive joins for: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/858 (Otherwise remove those querying features entirely, see below)~ *(2023-02-06: This would be nice, but isn’t really necessary.)*

    - [x] Remove any API parameters that can cause expensive table scanning (or require auth to use them). (https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/1070)

    - [x] ❌ ~Possibly do all the above as part of a v1 (instead of v0) API.~ *(Update: I wound up gating most features on being logged in rather than removing them, so I don’t think there’s a major reason to mess with versioning.)*

    - [x] Put the API behind CloudFront or API Gateway. (https://github.com/edgi-govdata-archiving/web-monitoring-ops/issues/42)

    - [x] Do not require auth for requests that *read* non-user-related tables. (https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/1069)

    - [x] Do not require auth when browsing the UI (https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/1025)

    - [x] Do not require credentials in Python DB client (https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/844)

- [x] Import reliability issues!

    - [x] Impose hard time limits on the import job in case it hangs (it does every so often, and *seems* to be some sort of issue in either Python requests/urllib3, but also 🤷). It’s possible a switch to httpx in [wayback](https://github.com/edgi-govdata-archiving/wayback/) could help alleviate this, but nothing except crashing the job after N hours is a true panacea. *(Done in https://github.com/edgi-govdata-archiving/web-monitoring-ops/commit/6c1ba742faccb393846757fb9e373c066380edae)*

    - [x] Run the importer on some kind of job scheduling system (Kube CronJob, GH Action via https://cirun.io, etc.) There’s this issue: https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/757 and Forest G had some nice thoughts about approaches for this kind of stuff in https://tinyletter.com/slow-news/letters/the-mgdo-stack (in particular, cirun.io looks lovely).

    - [x] Make sure we are using bigint (not int) for IDs here. (Should actually just do this for all tables with non-UUID primary keys) https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/1067

    - [x] ❌ ~(Maybe, not critical) import response bodies directly to S3 as part of the importer instead of as part of the API. https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/663~ *(2023-02-10: Not going to bother here; things are currently working fine enough.)*

- [x] ❌ ~(Maybe) Consider moving to either EKS or ECS + Terraform Cloud (free tier). Kops is super helpful for managing our own Kube deployment, but it’s still extra, complicated work that would be nice not to impose on anyone who has to touch or maintain this system later. This isn’t really critical, and may not pass the effort vs. return test when I get around to looking at it closely.~ *(2023-02-07: This is too big a change to be a reasonable when putting things to rest. It would be good and make things easier to maintain! But it’s too likely to cause other unknown issues and require time to settle out all the little things.)*

- [x] Turn off auto-annotation/analysis of imported versions in web-monitoring-db. (https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/1090)

- [x] Turn off metrics server. We aren’t actually using it, and it costs money to run (both the EC2 instance and the load balancer). https://github.com/edgi-govdata-archiving/web-monitoring-ops/issues/43

- [x] Turn off Dependabot updates (keep Dependebot *security* updates, though)

    - [x] web-monitoring-versionista-scraper
    - [x] web-monitoring-ui (https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/1040)
    - [x] web-monitoring-db (https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/1092)
    - [x] web-monitoring-processing (https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/848)

- [x] Shut down staging deployment (https://github.com/edgi-govdata-archiving/web-monitoring-ops/issues/45)

- [x] Documentation!

    - [x] ❌ ~Lessons learned from this project~ *(2023-07-17: Not doing this; not critical to shutdown.)*
    - [x] Why you probably don't want to use the tools here (and direct people to other options, see #18) *(Solved this as part of the main repo README notice, see below)*
    - [x] Add notes to all READMEs that these repos are no longer actively maintained
        - [x] web-monitoring edgi-govdata-archiving/web-monitoring#169
        - [x] web-monitoring-versionista-scraper https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/commit/1dd3845696c123c00d39595e606df7afde790d54
        - [x] web-monitoring-ui edgi-govdata-archiving/web-monitoring-ui#1045
        - [x] web-monitoring-db edgi-govdata-archiving/web-monitoring-db#1101
        - [x] web-monitoring-processing edgi-govdata-archiving/web-monitoring-processing#852

- [x] ❌ ~Maybe consider pulling out the Ruby SURT code into a gem. Not sure this is really worth while, though — I asked on the Internet Archive Slack last year and got back only responses that were essentially “that would be nice, but I don’t have real valuable use cases.”~ https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/767 *(2023-07-17: Not worrying about this as part of shutdown. It can always be revisited in the future; the source code is not going away.)*

- [x] ❌ ~Clean up dangling issues and PRs.~

- [x] ❌ ~Consider archiving some of the data here as WARC files, or outputting some archival data as SQLite or similar. I probably won’t actually do this (it’s not clear there’s much to gain from this work), but it’s at least worth investigating once everything else is done.~ *(2023-03-09: it doesn’t appear there’s much utility in doing this. The service continues to run and the database receives backups; the data is accessible for others to do this as a future project if desired.)*
