### ISSUE TITLE
☂ AWS Move Overview

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring#73]
This is an overview of the work we need to get operational stuff over to AWS from all various places things are currently running. (This does not cover PageFreezer work [separate timeline] or our redundant copy of Versionista data over at Google Cloud Storage [we plan to keep this indefinitely].)

- [x] Move the processing/diff server (edgi-govdata-archiving/web-monitoring-processing#95)
- [x] Move API server databases to RDS (edgi-govdata-archiving/web-monitoring-db#143)
- [x] Dockerize API server (edgi-govdata-archiving/web-monitoring-db#16)
- (probably more DB stuff to flesh out here)
- [x] Move running API code to EC2 (edgi-govdata-archiving/web-monitoring-db#144)
- [x] Move running UI code to EC2 (no issue for this yet; it’s fine if this one is a bit of a straggler—it’s cheap and isn’t overloaded)
- [x] Move scraping server
- [x] Migrate raw data from S3 (#101)
- [x] Decommission Heroku apps!

**Comment by Mr0grog** [comment]
Also worth noting here: we’re going to put everything in the `us-west-2` (Oregon) region.

At some point we’ll have to get smarter and:
- Create a proper private network so the outside world can’t talk to the DB or differs directly (we manage this purely through obscurity right now)
- Have fail-over resources in a different region

But we aren’t going to worry about either of those just quite yet.

**Comment by danielballan** [comment]
The IA servers are "based in the bay area" so that's a point in favor of us-west-1. For reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html

**Comment by danielballan** [comment]
Notes on my progress so far and future plans...

Goals:

* Make it easy to seamlessly update the production deployment and to launch multiple staging deployments, specifying specific commits/branches of the respective repos.
* Make it easier to do local development.

I think Kubernetes is a good fit for our architecture. Each of our components (db, processing, ui, scraper) can be deployed as a Service and scaled over multiple nodes as needed. Sub-components (redis, the import worker, the rails app) can be deployed as Containers within one Pod.

We can use minikube for local development (it uses one local VM node instead of a remote cluster of nodes).

Plan:
- [x] Containerize the Python diffing-server (web-monitoring-processing).
- [x] Deploy the diffing server as a Kubernetes Service.
- [x] Containerize the Rails app (one part of web-monitoring-db).
- [ ] Launch an RDS instance in us-west-2, and provide its config to the Rails app using a Kubernetes Secret object.
- [ ] Containerize the Redis worker (another part of web-monitoring-db)
- [ ] Launch the Rails app, Redis worker, and Redis server together as one Service.
- [ ] Containerize the React app (web-monitoring-ui).
- [ ] Launch the React app as a Service.
- [ ] Compose the three Services and the Secrets into a Helm Chart.
- [ ] Employ Helm's tools for unified access to logs.
- [ ] Likewise, deploy versionista-scraper and IA scraper as Services and incorporate them into the Chart.

Unanswered questions:
- How do Rails database migrations integrate with all this?
- Is swapping between RDS (production) and progres (dev) as easy as changing the connection parameters in secrets? (I think yes, but not sure.)

**Comment by danielballan** [comment]
Blockers for deploying production:
- [ ] Logs in CloudWatch
- [ ] Confirm Granan is still up, or decide that node-level metrics from AWS are enough for now
- [ ] Draft deployment docs

Long term:
- [ ] Move stateful services out (and maybe use ansible to help deploy those parts)
- [ ] Use LetsEncrypt instead of Amazon Cert Manager
- [ ] Make a Helm chart to work around config/secrets management pain points
- [ ] Write "launch your own WM deployment" docs

**Comment by danielballan** [comment]
> Confirm Granan is still up, or decide that node-level metrics from AWS are enough for now

Grfana is still running in the cluster (in its own namespace, confusingly named `monitoring`) but I don't like the way it's deployed. Things that monitor the cluster should live outside the cluster.

Separately, I had a quick chat with @b5 who has found that `kubectl` is sufficient for checking metrics. Grafana would be cool for have, but hearing @b5's experience getting along fine without it, now I think it's not even the highest-priority item on our "nice to have" list. I have edited the checklist accordingly.

That leaves logs and a draft of the docs as the only blockers before our planned move of production.

**Comment by Mr0grog** [comment]
All S3 data has been migrated over. 🎉

**Comment by Mr0grog** [comment]
This all all done! I’m leaving it open for a week with one extra checkbox: decommission the Heroku apps, which I will do on Friday, once we feel confident that things have been humming along nicely in production.
